<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
function common_theme(array $existing, $type, $theme, $path) {
  return array(
    'common_template' => array(
      'template' => 'common',
      'variables' => array(
        'variable1' => NULL,
      ),
    ),
  );
}

/**
 * Template preprocess function
 *
 * @param array $variables
 *   An associative array containing:
 *   - source_text
 */
function template_preprocess_common(&$variables) {

}

/*
 * Add JS for View blocks.
 */
function common_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->storage->id() == 'leadership' && $view->current_display == 'block_1') {
    $view->element['#attached']['library'][] = 'common/leadership_lib';
  }
  if ($view->storage->id() == 'board_of_directors' && $view->current_display == 'block_1') {
    $view->element['#attached']['library'][] = 'common/bod_lib';
  }
  if ($view->storage->id() == 'career_page_reviews' && $view->current_display == 'block_1') {
    $view->element['#attached']['library'][] = 'common/career-review';

 //get value ofimage fiel

  //$drupal_file_uri = File::load(63)->getFileUri();
  //print_r( file_url_transform_relative(file_create_url($drupal_file_uri)));
    $result = $view->result;

    foreach ($result as $i => $row) {

// set value of a fields
      $view->result[$i]->_entity->set('field_name', 'tessssssst');
      // get value of a field
      print_r($view->result[$i]->_entity->get('field_name')->value);
      //  $view->field['nothing']->options['alter']['text'] = 'My custom tesxt';
    }
  }
}

/*
 * Add Js for Main menu on every page
 */
function common_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'common/main-menu';
  $page['#attached']['library'][] = 'common/form-reload';
  
}