name: Configuration split
type: module
description: Configuration filter for importing and exporting split config
# core: 8.x
package: Config
configure: entity.config_split.collection
dependencies:
  - drupal:config_filter

# Information added by Drupal.org packaging script on 2017-08-24
version: '8.x-1.1'
core: '8.x'
project: 'config_split'
datestamp: 1503561861
